window.PARCOURS_CONFIG = {
  // Titre et sous-titre bilingues
  title: {
    fr: "Sentier botanique de Tréguier",
    en: "Tréguier botanical trail",
    de: "Botanischer Pfad von Tréguier",
    nl: "Botanisch pad van Tréguier"
  },
  subtitle: {
    fr: "Boucle au départ du village, 9 panneaux découverte",
    en: "Loop from the village, 9 discovery panels",
    de: "Rundweg ab dem Dorf, 9 Entdeckungstafeln",
    nl: "Lus vanaf het dorp, 9 ontdekkingsborden"
  },

  // Le reste de ta config ne bouge pas...
  gpx: "data/parcours.gpx",
  basemap:  "voyager", // topo, voyager, osm, positron
  showStats: true,
  editMode: false,
  photos: [],

  pois: [
    { lat: 43.847179, lng: 6.220829, logo: "images/bell-etoile-logo.png", badgeFr: "🏡 Votre séjour", badgeEn: "🏡 Your stay", badgeDe: "🏡 Ihr Aufenthalt", badgeNl: "🏡 Uw verblijf", titleFr: "Bell'Étoile", titleEn: "Bell'Étoile", titleDe: "Bell'Étoile", titleNl: "Bell'Étoile", descFr: "Moustiers-Sainte-Marie, Provence", descEn: "Moustiers-Sainte-Marie, Provence", descDe: "Moustiers-Sainte-Marie, Provence", descNl: "Moustiers-Sainte-Marie, Provence" },
    { lat: 43.772767, lng: 6.207962, logo: "images/bellodulac-logo.png", badgeFr: "🏡 Votre séjour", badgeEn: "🏡 Your stay", badgeDe: "🏡 Ihr Aufenthalt", badgeNl: "🏡 Uw verblijf", titleFr: "Bell'O du Lac", titleEn: "Bell'O du Lac", titleDe: "Bell'O du Lac", titleNl: "Bell'O du Lac", descFr: "Salles sur Verdon", descEn: "Salles sur Verdon", descDe: "Salles sur Verdon", descNl: "Salles sur Verdon" },
    { lat: 43.84556937774747, lng: 6.222341599449604, logo: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCI+PHRleHQgeD0iMzIiIHk9IjQ2IiBmb250LXNpemU9IjM4IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj7wn4+6PC90ZXh0Pjwvc3ZnPg==", badgeFr: "Savoir-faire", badgeEn: "Craft", badgeDe: "Handwerk", badgeNl: "Vakmanschap", titleFr: "La fa\u00efence de Moustiers", titleEn: "Moustiers faience pottery", titleDe: "Die Fayence von Moustiers", titleNl: "Het faience-aardewerk van Moustiers", descFr: "La renomm\u00e9e de Moustiers ne tient pas seulement \u00e0 son site, aussi exceptionnel soit-il. Pour de nombreux connaisseurs, Moustiers est synonyme d'art de la fa\u00efence et les pi\u00e8ces anciennes \u201cen Moustiers\u201d, qui comptent parmi les plus fines fa\u00efences de France, sont extr\u00eamement recherch\u00e9es des connaisseurs. De nombreux mus\u00e9es, de nombreux ch\u00e2teaux ou maisons aristocratiques poss\u00e8dent une ou plusieurs pi\u00e8ces anciennes de Moustiers. On peut en admirer au Mus\u00e9e de S\u00e8vres, au mus\u00e9e de Lyon, au Louvre.", descEn: "Moustiers' renown isn't only due to its exceptional setting. For many connoisseurs, Moustiers is synonymous with faience pottery, and the antique pieces \u201cfrom Moustiers\u201d \u2014 among the finest earthenware in France \u2014 are highly sought after by collectors. Many museums, ch\u00e2teaux and aristocratic homes own one or more antique Moustiers pieces, on display at the S\u00e8vres Museum, the Lyon Museum and the Louvre.", descDe: "Der Ruf von Moustiers beruht nicht nur auf seiner au\u00dfergew\u00f6hnlichen Lage. F\u00fcr viele Kenner ist Moustiers gleichbedeutend mit der Kunst der Fayence: Die alten St\u00fccke \u201eaus Moustiers\u201c, die zu den feinsten Fayencen Frankreichs z\u00e4hlen, sind bei Sammlern sehr gefragt. Zahlreiche Museen, Schl\u00f6sser und Adelsh\u00e4user besitzen ein oder mehrere alte St\u00fccke aus Moustiers, zu bewundern im Mus\u00e9e de S\u00e8vres, im Museum von Lyon und im Louvre.", descNl: "De faam van Moustiers is niet alleen te danken aan zijn uitzonderlijke ligging. Voor veel kenners staat Moustiers gelijk aan de kunst van het faience-aardewerk: de antieke stukken \u201cuit Moustiers\u201d, die tot het fijnste aardewerk van Frankrijk behoren, zijn bij verzamelaars zeer gewild. Veel musea, kastelen en adellijke huizen bezitten een of meerdere antieke stukken uit Moustiers, te bewonderen in het Mus\u00e9e de S\u00e8vres, het museum van Lyon en het Louvre." },
    { lat: 43.8450397348661, lng: 6.222305366544791, logo: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCI+PHRleHQgeD0iMzIiIHk9IjQ2IiBmb250LXNpemU9IjM4IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj7wn4+b77iPPC90ZXh0Pjwvc3ZnPg==", badgeFr: "Patrimoine et histoire", badgeEn: "Heritage & history", badgeDe: "Kulturerbe & Geschichte", badgeNl: "Erfgoed & geschiedenis", titleFr: "Chapelle Sainte-Anne", titleEn: "Sainte-Anne chapel", titleDe: "Kapelle Sainte-Anne", titleNl: "Kapel Sainte-Anne", descFr: "Cette chapelle a \u00e9t\u00e9 construite au XVIe si\u00e8cle, sur l'emplacement d'une chapelle du XIIe si\u00e8cle, avec des mat\u00e9riaux de r\u00e9cup\u00e9ration provenant des tours et remparts devenus inutiles.", descEn: "This chapel was built in the 16th century, on the site of a 12th-century chapel, using reclaimed materials from the towers and ramparts that had become obsolete.", descDe: "Diese Kapelle wurde im 16. Jahrhundert an der Stelle einer Kapelle aus dem 12. Jahrhundert errichtet, mit wiederverwendeten Materialien der \u00fcberfl\u00fcssig gewordenen T\u00fcrme und Stadtmauern.", descNl: "Deze kapel werd in de 16e eeuw gebouwd op de plaats van een kapel uit de 12e eeuw, met hergebruikte materialen van de torens en stadsmuren die overbodig waren geworden." },
    { lat: 43.8443547198234, lng: 6.222886204632231, logo: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCI+PHRleHQgeD0iMzIiIHk9IjQ2IiBmb250LXNpemU9IjM4IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj7wn4y/PC90ZXh0Pjwvc3ZnPg==", badgeFr: "Flore", badgeEn: "Flora", badgeDe: "Flora", badgeNl: "Flora", titleFr: "\u00abMets de l'huile !\u00bb", titleEn: "\"Put some oil in it!\"", titleDe: "\u201eGib \u00d6l dazu!\u201c", titleNl: "\"Doe er olie bij!\"", descFr: "M\u00eame si sa pr\u00e9sence naturelle reste discut\u00e9e, des \u00e9tudes g\u00e9n\u00e9tiques sont en cours pour essayer de retrouver son berceau, l'olivier est devenu indissociable des paysages de Provence. Largement plant\u00e9 partout o\u00f9 il accepte de se d\u00e9velopper, son aire de r\u00e9partition est souvent utilis\u00e9e par les botanistes pour d\u00e9finir la zone climatique \u201cm\u00e9diterran\u00e9enne\u201d. Olives vertes et olives noires proviennent du m\u00eame arbre, la diff\u00e9rence provient de l'\u00e9poque de la r\u00e9colte.", descEn: "Even though its natural presence is still debated, genetic studies are underway to try to trace its origin: the olive tree has become inseparable from the landscapes of Provence. Widely planted wherever it can grow, its range is often used by botanists to define the \u201cMediterranean\u201d climate zone. Green and black olives come from the same tree \u2014 the difference comes from when they are harvested.", descDe: "Auch wenn seine nat\u00fcrliche Verbreitung noch umstritten ist und genetische Studien laufen, um seinen Ursprung zu kl\u00e4ren: Der Olivenbaum ist aus den Landschaften der Provence nicht mehr wegzudenken. Weit verbreitet, wo immer er gedeihen kann, wird sein Verbreitungsgebiet von Botanikern oft genutzt, um die \u201emediterrane\u201c Klimazone zu definieren. Gr\u00fcne und schwarze Oliven stammen vom selben Baum \u2013 der Unterschied liegt im Erntezeitpunkt.", descNl: "Ook al staat zijn natuurlijke aanwezigheid nog ter discussie en lopen er genetische studies om zijn oorsprong te achterhalen: de olijfboom is niet meer weg te denken uit de landschappen van de Provence. Overal geplant waar hij kan groeien, wordt zijn verspreidingsgebied door botanici vaak gebruikt om de \u201cmediterrane\u201d klimaatzone te defini\u00ebren. Groene en zwarte olijven komen van dezelfde boom \u2014 het verschil zit in het oogsttijdstip." },
    { lat: 43.84398806453275, lng: 6.223641436122875, logo: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCI+PHRleHQgeD0iMzIiIHk9IjQ2IiBmb250LXNpemU9IjM4IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj7wn4+e77iPPC90ZXh0Pjwvc3ZnPg==", badgeFr: "Point de vue", badgeEn: "Viewpoint", badgeDe: "Aussichtspunkt", badgeNl: "Uitzichtpunt", titleFr: "Lecture de paysage", titleEn: "Reading the landscape", titleDe: "Landschaft lesen", titleNl: "Het landschap lezen", descFr: "La lecture et l'\u00e9tude des paysages permet de toucher de nombreuses th\u00e9matiques transversales comme la biodiversit\u00e9, l'histoire, la g\u00e9ographie, l'environnement, l'\u00e9conomie.", descEn: "Reading and studying landscapes touches on many cross-cutting themes such as biodiversity, history, geography, environment and economy.", descDe: "Das Lesen und Erforschen von Landschaften ber\u00fchrt zahlreiche \u00fcbergreifende Themen wie Biodiversit\u00e4t, Geschichte, Geografie, Umwelt und Wirtschaft.", descNl: "Het lezen en bestuderen van landschappen raakt aan tal van overkoepelende thema's zoals biodiversiteit, geschiedenis, geografie, milieu en economie." },
    { lat: 43.84338615828133, lng: 6.223624634646295, logo: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCI+PHRleHQgeD0iMzIiIHk9IjQ2IiBmb250LXNpemU9IjM4IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj7wn4+b77iPPC90ZXh0Pjwvc3ZnPg==", badgeFr: "Patrimoine et histoire", badgeEn: "Heritage & history", badgeDe: "Kulturerbe & Geschichte", badgeNl: "Erfgoed & geschiedenis", titleFr: "Les bancau de Moustiers", titleEn: "The 'bancau' terraces of Moustiers", titleDe: "Die \u201ebancau\u201c-Terrassen von Moustiers", titleNl: "De \u2018bancau\u2019-terrassen van Moustiers", descFr: "Le terme proven\u00e7al bancau (prononc\u00e9 bancaou) signifie au sens propre \u00ab plate-bande \u00bb, \u00ab planche cultiv\u00e9e \u00bb, et au sens large \u00ab gradin de culture \u00bb ; ici \u00e0 Moustiers, une belle oliveraie est cultiv\u00e9e. Une oliveraie est un verger plant\u00e9 d'oliviers, essentiellement pour l'ol\u00e9iculture et la production d'huile d'olive. Les oliveraies sont principalement situ\u00e9es dans les pays du bassin m\u00e9diterran\u00e9en ainsi qu'au Proche-Orient. On trouve des oliveraies en Provence, dans le sud de la France.", descEn: "The Proven\u00e7al word \"bancau\" (pronounced bancaou) literally means \"flowerbed\" or \"cultivated bed\", and more broadly a \"cultivation terrace\" \u2014 here in Moustiers, a beautiful olive grove is cultivated this way. An olive grove is an orchard planted with olive trees, mainly for olive growing and olive oil production. Olive groves are found mainly around the Mediterranean basin and the Near East, including here in Provence, in the south of France.", descDe: "Das provenzalische Wort \u201ebancau\u201c (ausgesprochen bancaou) bedeutet w\u00f6rtlich \u201eBeet\u201c oder \u201eangelegtes Kulturfeld\u201c, im weiteren Sinne eine \u201eAnbauterrasse\u201c \u2013 hier in Moustiers wird auf diese Weise ein sch\u00f6ner Olivenhain bewirtschaftet. Ein Olivenhain ist eine mit Olivenb\u00e4umen bepflanzte Obstplantage, haupts\u00e4chlich f\u00fcr den Olivenanbau und die Oliven\u00f6lproduktion. Olivenhaine findet man vor allem im Mittelmeerraum sowie im Nahen Osten, so auch hier in der Provence im S\u00fcden Frankreichs.", descNl: "Het Proven\u00e7aalse woord \"bancau\" (uitgesproken als bancaou) betekent letterlijk \"border\" of \"aangelegd perceel\", en in bredere zin een \"cultuurterras\" \u2014 hier in Moustiers wordt op deze manier een prachtige olijfgaard onderhouden. Een olijfgaard is een boomgaard beplant met olijfbomen, voornamelijk voor de olijfteelt en de productie van olijfolie. Olijfgaarden vindt men vooral rond het Middellandse Zeegebied en in het Nabije Oosten, ook hier in de Provence, in het zuiden van Frankrijk." },
    { lat: 43.84125877528923, lng: 6.223980996239708, logo: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCI+PHRleHQgeD0iMzIiIHk9IjQ2IiBmb250LXNpemU9IjM4IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj7wn4y/PC90ZXh0Pjwvc3ZnPg==", badgeFr: "Flore", badgeEn: "Flora", badgeDe: "Flora", badgeNl: "Flora", titleFr: "Les pupitres", titleEn: "The information panels", titleDe: "Die Infotafeln", titleNl: "De informatieborden", descFr: "De nombreux pupitres vous informeront sur la flore pr\u00e9sente sur le parcours.", descEn: "Numerous information panels along the way will tell you about the flora found on the route.", descDe: "Zahlreiche Infotafeln entlang des Weges informieren Sie \u00fcber die Flora entlang der Strecke.", descNl: "Talrijke informatieborden onderweg vertellen u over de flora langs het parcours." },
    { lat: 43.83916372438554, lng: 6.226928265421007, logo: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCI+PHRleHQgeD0iMzIiIHk9IjQ2IiBmb250LXNpemU9IjM4IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj7wn6qoPC90ZXh0Pjwvc3ZnPg==", badgeFr: "G\u00e9ologie", badgeEn: "Geology", badgeDe: "Geologie", badgeNl: "Geologie", titleFr: "Petit \u00e9ductour", titleEn: "A short geology tour", titleDe: "Kleine geologische Entdeckungstour", titleNl: "Korte geologische ontdekkingstocht", descFr: "Le parcours, parsem\u00e9 de pupitres, vous informera sur la g\u00e9ologie du lieu.", descEn: "The route, dotted with information panels, will tell you about the geology of the area.", descDe: "Die mit Infotafeln ges\u00e4umte Strecke informiert Sie \u00fcber die Geologie des Gebiets.", descNl: "Het parcours, met informatieborden onderweg, vertelt u over de geologie van de streek." },
    { lat: 43.836025765052064, lng: 6.2331017045994255, logo: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCI+PHRleHQgeD0iMzIiIHk9IjQ2IiBmb250LXNpemU9IjM4IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj7wn4+e77iPPC90ZXh0Pjwvc3ZnPg==", badgeFr: "Point de vue", badgeEn: "Viewpoint", badgeDe: "Aussichtspunkt", badgeNl: "Uitzichtpunt", titleFr: "Vue depuis le belv\u00e9d\u00e8re", titleEn: "View from the belvedere", titleDe: "Blick vom Aussichtspunkt", titleNl: "Uitzicht vanaf het belved\u00e8re", descFr: "Une vue plongeante sur le lac de Sainte-Croix.", descEn: "A sweeping view over Lake Sainte-Croix.", descDe: "Ein weiter Blick auf den Lac de Sainte-Croix.", descNl: "Een weids uitzicht over het meer van Sainte-Croix." },
    { lat: 43.8341901273543, lng: 6.234516084150527, logo: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA2NCA2NCI+PHRleHQgeD0iMzIiIHk9IjQ2IiBmb250LXNpemU9IjM4IiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj7wn4+e77iPPC90ZXh0Pjwvc3ZnPg==", badgeFr: "Point de vue", badgeEn: "Viewpoint", badgeDe: "Aussichtspunkt", badgeNl: "Uitzichtpunt", titleFr: "Le Val d'Angouire", titleEn: "The Val d'Angouire", titleDe: "Das Val d\u2019Angouire", titleNl: "Het Val d\u2019Angouire", descFr: "Sur votre droite, au fond du ravin, vous apercevrez le Val d'Angouire, qui sert de parcours pour la pratique du canyoning, certainement l'un des plus sauvages des gorges du Verdon, avec celui de Main Morte. Son acc\u00e8s, relativement long, en fait un parcours pr\u00e9serv\u00e9, peu fr\u00e9quent\u00e9 et accessible \u00e0 tous.", descEn: "On your right, at the bottom of the ravine, you'll spot the Val d'Angouire, used for canyoning \u2014 certainly one of the wildest gorges in the Verdon area, along with Main Morte. Its relatively long approach makes it an unspoiled, little-visited route, accessible to everyone.", descDe: "Rechts am Grund der Schlucht erblicken Sie das Val d'Angouire, das f\u00fcr Canyoning genutzt wird \u2013 zusammen mit der Main Morte sicherlich eine der wildesten Schluchten des Verdon. Der relativ lange Zustieg macht sie zu einer unber\u00fchrten, wenig besuchten und f\u00fcr alle zug\u00e4nglichen Route.", descNl: "Aan uw rechterkant, onderin de kloof, ziet u het Val d'Angouire, dat wordt gebruikt voor canyoning \u2014 samen met Main Morte ongetwijfeld een van de meest ongerepte kloven van de Verdon. De relatief lange toegang maakt het tot een goed bewaard, weinig bezocht en voor iedereen toegankelijk parcours." }
  ]
};
